methods:
  CatBoost:
    enabled: true
    model_type: "catboost_classifier"
    params:
      iterations: 100
      learning_rate: 0.1
      depth: 3
      random_state: 42
      silent: true

  XGBoost:
    enabled: true
    model_type: "xgb_classifier"
    params:
      n_estimators: 200
      learning_rate: 0.05
      max_depth: 4
      random_state: 42
      use_label_encoder: false
      eval_metric: "mlogloss"

  LightGBM:
    enabled: true
    model_type: "lgbm_classifier"
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      random_state: 42

  AdaBoost:
    enabled: true
    model_type: "adaboost_classifier"
    params:
      n_estimators: 100
      learning_rate: 0.1
      random_state: 42
      base_estimator: "decision_tree"
      base_estimator_params:
        max_depth: 1

  # <TODO> Add Geogry's Boosting methods

output_settings:
  results_dir: "results"

logging:
  level: "info"
