experiments:
  - name: "Exp1_Synthetic_small"
    data:
      type: "synthetic"
      task: "classification"
      params:
        n_samples: 1000
        n_features: 2
        random_state: 42
    methods:
      - "CatBoost"
      - "XGBoost"
      - "AdaBoost"

  - name: "Exp2_Synthetic_hard"
    data:
      type: "synthetic"
      task: "classification"
      params:
        n_samples: 10000
        n_features: 20
        random_state: 42
    methods:
      - "CatBoost"
      - "LightGBM"

  - name: "Exp3_RealDataset"
    data:
      type: "csv"
      path: "datasets/some_real_data.csv"
      target_column: "label"
    methods:
      - "CatBoost"
      - "XGBoost"
      - "AdaBoost"
